# Generated by Django 5.0.4 on 2024-04-19 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User_Management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user_management",
            name="Address",
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user_management",
            name="Batch_Time",
            field=models.CharField(
                choices=[
                    ("morning", "Morning"),
                    ("afternoon", "Afternoon"),
                    ("evening", "Evening"),
                    ("weekends", "Weekends"),
                ],
                default=None,
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user_management",
            name="Blood_Group",
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user_management",
            name="Height",
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user_management",
            name="Medical_Issue",
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user_management",
            name="Mobile_No",
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user_management",
            name="Reason_For_Joining",
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user_management",
            name="Subscription_Date_From",
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user_management",
            name="Subscription_Date_To",
            field=models.DateField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user_management",
            name="Taking_Medicine",
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user_management",
            name="Weight",
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user_management",
            name="Subscription_Type",
            field=models.CharField(
                choices=[
                    ("kids", "Kids"),
                    ("adult", "Adult"),
                    ("personal_training", "Personal Training"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
    ]
