# Generated by Django 5.0.4 on 2024-04-24 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Management', '0002_user_management_address_user_management_batch_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_management',
            name='Blood_Group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('other', 'Other')], max_length=10),
        ),
    ]
