# Generated by Django 5.0.4 on 2024-06-26 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_Management', '0003_alter_user_management_blood_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_management',
            options={'verbose_name_plural': 'Student Information'},
        ),
    ]
