# Generated by Django 5.0.4 on 2024-04-18 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='description',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='para_title',
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='paragraph_description',
            field=models.TextField(default='Describe about your title mentioned above...'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='paragraph_title',
            field=models.CharField(default='Enter title here...', max_length=50),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='bio',
            field=models.TextField(default='Tell about yourself here...'),
        ),
    ]
