# Generated by Django 5.0.4 on 2024-04-18 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0003_hyperlinks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_archivements', models.CharField(max_length=120, verbose_name='awards and archivements')),
            ],
        ),
    ]
