# Generated by Django 5.0.4 on 2024-04-18 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0004_archivements'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archivements',
            old_name='_archivements',
            new_name='archivements',
        ),
    ]
