# Generated by Django 5.0.4 on 2024-04-18 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0005_rename__archivements_archivements_archivements'),
    ]

    operations = [
        migrations.AddField(
            model_name='hyperlinks',
            name='linkdin',
            field=models.CharField(max_length=50, null=True, verbose_name='linkdin link'),
        ),
        migrations.AddField(
            model_name='hyperlinks',
            name='twiter',
            field=models.CharField(default=None, max_length=1024, verbose_name='twiter link'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hyperlinks',
            name='facebook',
            field=models.CharField(default=None, max_length=200, null=True, verbose_name='facebook link'),
        ),
    ]
