# Generated by Django 5.0.4 on 2024-04-20 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0008_alter_hyperlinks_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='img',
            field=models.ImageField(default='static/img/classes/1.jpg', height_field=283, max_length=150, upload_to='src/media/about/', verbose_name='image', width_field=282),
        ),
    ]
