# Generated by Django 5.0.4 on 2024-04-20 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0009_aboutpage_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='InquiryDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50, verbose_name='fname')),
                ('lname', models.CharField(max_length=50, verbose_name='lname')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('description', models.TextField(verbose_name='description')),
            ],
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='img',
            field=models.ImageField(default='static/img/classes/1.jpg', max_length=150, upload_to='src/media/about/', verbose_name='image'),
        ),
    ]
