# Generated by Django 5.0.4 on 2024-04-20 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0010_inquirydetails_alter_aboutpage_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquirydetails',
            name='mobile',
            field=models.BigIntegerField(default=None, verbose_name='mobile'),
            preserve_default=False,
        ),
    ]
