# Generated by Django 5.0.4 on 2024-04-23 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0011_inquirydetails_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_image', models.ImageField(upload_to='src/media/gallery/', verbose_name='Gallery Image')),
            ],
        ),
    ]
