# Generated by Django 5.0.4 on 2024-06-26 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0012_gallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutpage',
            options={'verbose_name_plural': 'About Page Information'},
        ),
        migrations.AlterModelOptions(
            name='archivements',
            options={'verbose_name_plural': 'Achivements'},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name_plural': "Gallery Image's"},
        ),
        migrations.AlterModelOptions(
            name='hyperlinks',
            options={'verbose_name_plural': 'Hyperlinks'},
        ),
        migrations.AlterModelOptions(
            name='inquirydetails',
            options={'verbose_name_plural': 'Inquiry Details'},
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='img',
            field=models.ImageField(default=None, max_length=150, upload_to=None, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='gallery_image',
            field=models.ImageField(upload_to=None, verbose_name='Gallery Image'),
        ),
    ]
