# Generated by Django 5.0.4 on 2024-06-27 07:48

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Event title')),
                ('date', models.DateTimeField(verbose_name='Date and Time of the event')),
                ('image', models.ImageField(default='staticfiles/static/img/classes/3.jpg', max_length=150, upload_to=None, verbose_name='Image')),
                ('time', models.PositiveIntegerField(default=60, verbose_name='Total event time (duration):')),
                ('description', tinymce.models.HTMLField()),
            ],
            options={
                'verbose_name_plural': 'Evnets',
            },
        ),
    ]
