# Generated by Django 5.0.4 on 2024-06-27 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'verbose_name_plural': 'Events'},
        ),
        migrations.AddField(
            model_name='events',
            name='slug',
            field=models.SlugField(default=None, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='time',
            field=models.PositiveIntegerField(default=60, verbose_name='Total event time (duration in minutes):'),
        ),
    ]
