# Generated by Django 5.0.4 on 2024-07-01 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_events_options_events_slug_alter_events_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='slug',
            field=models.SlugField(default=None, null=True, unique=True),
        ),
    ]
