# Generated by Django 5.0.4 on 2024-04-19 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_title', models.CharField(max_length=50, verbose_name='class title')),
                ('class_week', models.CharField(max_length=50, verbose_name='enter week')),
                ('class_time', models.CharField(max_length=50, verbose_name='enter time')),
                ('class_description', models.TextField(verbose_name='enter description')),
            ],
        ),
    ]
