# Generated by Django 5.0.4 on 2024-04-20 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="classinfo",
            name="class_img",
            field=models.ImageField(
                default="/img/classes/3.jpg",
                height_field="283",
                max_length=150,
                upload_to="classes",
                verbose_name="image",
                width_field=283,
            ),
        ),
    ]
