# Generated by Django 5.0.4 on 2024-04-20 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_alter_classinfo_class_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classinfo',
            name='class_img',
            field=models.ImageField(default='static/img/classes/3.jpg', max_length=150, upload_to='src/media/classes/', verbose_name='image'),
        ),
    ]
