# Generated by Django 5.0.4 on 2024-06-26 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_alter_classinfo_class_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classinfo',
            options={'verbose_name': 'Classes Information'},
        ),
        migrations.AlterField(
            model_name='classinfo',
            name='class_img',
            field=models.ImageField(default='staticfiles/static/img/classes/3.jpg', max_length=150, upload_to=None, verbose_name='image'),
        ),
    ]
